name: Test Trivy

on:
  push:
    branches:
      - main

jobs:
  build_and_test_mi:
    runs-on: self-hosted
    name: Scan MI/APIM Image
    steps:
      - name: Test Trivy MI vuln scan
        run: |
          trivy image --scanners vuln --format table --severity HIGH,CRITICAL  --exit-code 0 wso2/wso2mi:4.3.0-alpine

      - name: Test Trivy MI Secret scan
        run: |
          trivy image --scanners secret --format table --severity HIGH,CRITICAL  --exit-code 0 wso2/wso2mi:4.3.0-alpine

      - name: Test Trivy APIM vuln scan
        run: |
          trivy image --scanners vuln --format table --severity HIGH,CRITICAL  --exit-code 0 wso2/wso2am:4.3.0-rocky

      - name: Test Trivy APIM Secret scan
        run: |
          trivy image --scanners secret --format table --severity HIGH,CRITICAL  --exit-code 0 wso2/wso2am:4.3.0-rocky


