name: Test Trivy

on:
  push:
    branches:
      - main

jobs:
  build_and_test_mi:
    runs-on: self-hosted
    name: Build MI Image
    permissions:
      contents: read
      security-events: write
    outputs:
      mi_image_name: ${{ steps.test_mi_image.outputs.mi_image_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build, tag, and push docker image to Amazon ECR
        id: test_mi_image
        run: |
          echo "Building image and pushing to Amazon ECR"
          echo "mi_image_name=wso2/wso2am" >> "$GITHUB_OUTPUT"

      - name: Test Trivy MI vuln scan
        run: |
          trivy image --scanners vuln --format table --severity HIGH,CRITICAL  --exit-code 1 ${{ steps.test_mi_image.outputs.mi_image_name }}

      - name: Test Trivy MI Secret scan
        run: |
          trivy image --scanners secret --format table --severity HIGH,CRITICAL  --exit-code 1 ${{ steps.test_mi_image.outputs.mi_image_name }}

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v4
      #   if: always()
      #   with:
      #     sarif_file: "trivy-results-mi-vuln.sarif"
      #     category: mi-results-vuln-scan

      # - name: Test Trivy MI secret scan
      #   uses: aquasecurity/trivy-action@0.33.1
      #   with:
      #     image-ref: ${{ steps.test_mi_image.outputs.mi_image_name }}
      #     format: "sarif"
      #     exit-code: "1"
      #     ignore-unfixed: true
      #     scanners: "secret"
      #     output: "trivy-results-mi-secret.sarif"

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v4
      #   if: always()
      #   with:
      #     sarif_file: "trivy-results-mi-secret.sarif"
      #     category: mi-results-secret-scan
